trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: PowerApps-SP-Secrets
  - name: environmentId
    value: '493ec420-26dc-ebc2-9bc0-11821149f051'
  - name: tenantId
    value: '5a926f23-0839-4500-b4b8-d0dec88134c1'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 8'
    inputs:
      version: 8.0.x

  - task: DotNetCoreCLI@2
    displayName: 'Build Test Engine'
    inputs:
      command: 'build'
      projects: 'src/PowerAppsTestEngine.sln'

  - script: |
      pwsh src/bin/Debug/PowerAppsTestEngine/playwright.ps1 install
    displayName: 'Install Playwright browsers'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'run'
      workingDirectory: 'src/PowerAppsTestEngine'
    env:
      POWERAPPS_ENVIRONMENT_ID: $(environmentId)
      POWERAPPS_TENANT_ID: $(tenantId)
      POWERAPPS_TEST_ACCOUNT_USER: $(testAccountUser)
      POWERAPPS_TEST_ACCOUNT_PASSWORD: $(testAccountPassword)

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      failTaskOnFailedTests: true
    condition: always()
